import Head from 'next/head'
import styles from '../styles/Azul.module.scss'

export default function Azul() {
  const streamingPlatformsLinks = 'https://ffm.to/marteemarcianas'

  return (
    <div className={styles.container}>
      <Head>
        <title>Azul by Vilarezz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section>
        <div className={styles.shortInfo}>
          <img src="/azul-logo.svg" alt="Azul by Gil Vilarezz" />
          <p>Tracklist</p>
        </div>

        <div className={styles.cards}>
          <a href={streamingPlatformsLinks} className={styles.card}>
            <img src="/Card.png" alt="" />
          </a>
          <a href={streamingPlatformsLinks} className={styles.card}>
            <img src="/Card-1.png" alt="" />
          </a>
          <a href={streamingPlatformsLinks} className={styles.card}>
            <img src="/Card-2.png" alt="" />
          </a>
        </div>

        <div className={styles.callToAction}>
          <h4>
            Escute na sua <br /> plataforma favorita
          </h4>
          <a href="#" className={styles.btn}>
            CLICA PARA VIAJAR 🚀
          </a>
        </div>
      </section>
    </div>
  )
}
